name: test-workflow

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: test-file.txt
          key: cache-key

      - name: Print env
        run: echo "$obj"
        env:
          obj: ${{ toJson(github) }}

      - name: Create file
        run: |
          echo "Hello, world!" > test-file.txt
