name: test-workflow

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: test-file.txt
          key: cache-key

      - name: Create file
        run: |
          echo "Hello, world!" > test-file.txt
