name: workflow-run

on:
  workflow_run:
    workflows:
      - test-workflow
    types:
      - completed

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: echo "$obj"
        env:
          obj: ${{ toJson(github.event) }}

      - name: Print event
        run: echo "event = ${{ github.event.workflow_run.event }}"

      - name: Check if pull_request
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        run: echo "PR number = ${{ github.event.workflow_run.pull_requests[0].number }}"

      - name: Check if push
        if: ${{ github.event.workflow_run.event == 'push' }}
        run: echo "branch = ${{ github.event.workflow_run.head_branch }}"

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: test-file.txt
          key: cache-key

      - name: Print file
        run: |
          cat test-file.txt
